{% set name = "psycopg-pool" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bb942f123bef4b7fbe4d55421bd3fb01829903c95c0f33fd42b7e94e5ac9b52a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=49.2.0
    - pip
  run:
    - python >=3.8
    - typing-extensions >=4.4

test:
  imports:
    - psycopg_pool
  commands:
    - pip check
  requires:
    - pip
    - psycopg >=3.0

about:
  home: https://psycopg.org/psycopg3/
  summary: Connection Pool for Psycopg
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://www.psycopg.org/psycopg3/docs/advanced/pool.html
  dev_url: https://github.com/psycopg/psycopg/

extra:
  recipe-maintainers:
    - xylar
